version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        volumes:
            - "$PWD/config:/tmp"
    db:
        image: "postgres"
        environment:
            POSTGRES_USER: anciens
            POSTGRES_PASSWORD: password
        volumes:
            - "anciens-db:/var/lib/postgresql/data"

volumes:
    anciens-db:
